import { PayRollDTO } from "../entities/payRoll";

const mapperPayRoll = (data: any): PayRollDTO => {
  return {
    id: data.Id,
    ParceriaId: data.ParceriaId,
    PrestacaoContaId: data.PrestacaoContaId,
    FuncionarioId: data.FuncionarioId,
    Nome: data.Nome,
    CPF: data.CPF,
    DataNascimento: new Date(data.DataNascimento),
    CargoId: data.CargoId,
    TipoColaborador: data.TipoColaborador,
    TipoCoordenadoria: data.TipoCoordenadoria,
    RegimeContratacao: data.RegimeContratacao,
    CnsDoProfissional: data.CnsDoProfissional,
    TipoAtividade: data.TipoAtividade,
    TipoFolha: data.TipoFolha,
    TipoJornada: data.TipoJornada,
    FuncaoId: data.FuncaoId,
    DataAdmissao: new Date(data.DataAdmissao),
    DataDesligamento: new Date(data.DataDesligamento),
    NumConselhoClasse: data.NumConselhoClasse,
    AutoDeclaracaoRacial: data.AutoDeclaracaoRacial,
    NomeSocial: data.NomeSocial,
    AutoDeclaracaoGenero: data.AutoDeclaracaoGenero,
    Especificacao: data.Especificacao,
    SalarioBase: data.SalarioBase,
    SalarioBruto: data.SalarioBruto,
    SalarioLiquido: data.SalarioLiquido,
    Gratificacao: data.Gratificacao,
    HorasExtras: data.HorasExtras,
    HorasExtrasDsr: data.HorasExtrasDsr,
    AdicionalNoturno: data.AdicionalNoturno,
    AdicionalNoturnoDsr: data.AdicionalNoturnoDsr,
    Premio: data.Premio,
    AdicionalPericulosidade: data.AdicionalPericulosidade,
    AdicionalInsalubridade: data.AdicionalInsalubridade,
    DiferencaSalarial: data.DiferencaSalarial,
    SalarioFamilia: data.SalarioFamilia,
    SalarioMaternidade: data.SalarioMaternidade,
    RestituicaoInss: data.RestituicaoInss,
    RestituicaoIrrf: data.RestituicaoIrrf,
    AdiantamentoSalario: data.AdiantamentoSalario,
    Devolucao: data.Devolucao,
    Arredondamento: data.Arredondamento,
    AtestadoAteQuinzeDias: data.AtestadoAteQuinzeDias,
    OutrosProventos: data.OutrosProventos,
    Ferias: data.Ferias,
    FeriaAbono: data.FeriaAbono,
    FeriasProximoMes: data.FeriasProximoMes,
    AbonoPecuniario: data.AbonoPecuniario,
    DecimoTerceiroPrimeiraParcela: data.DecimoTerceiroPrimeiraParcela,
    DecimoTerceiroSegundaParcela: data.DecimoTerceiroSegundaParcela,
    SaldoSalarioRescisao: data.SaldoSalarioRescisao,
    FeriasProporcionaisRescisao: data.FeriasProporcionaisRescisao,
    FeriasProporcionaisRescisaoUmTercoAdicional:
      data.FeriasProporcionaisRescisaoUmTercoAdicional,
    DecimoTerceiroProporcionalRescisao: data.DecimoTerceiroProporcionalRescisao,
    DecimoTerceiroIndenizado: data.DecimoTerceiroIndenizado,
    MultaRescisao: data.MultaRescisao,
    OutrasVerbasRescisorias: data.OutrasVerbasRescisorias,
    ValorBrutoRescisao: data.ValorBrutoRescisao,
    ValorLiquidoRescisaoAPagar: data.ValorLiquidoRescisaoAPagar,
    PlantaoMensal: data.PlantaoMensal,
    ValeTransporte: data.ValeTransporte,
    ValeAlimentacao: data.ValeAlimentacao,
    ValeRefeicao: data.ValeRefeicao,
    CestaBasica: data.CestaBasica,
    AuxilioCreche: data.AuxilioCreche,
    Auxilios: data.Auxilios,
    OutrosBeneficios: data.OutrosBeneficios,
    DescontosInss: data.DescontosInss,
    DescontosInssFerias: data.DescontosInssFerias,
    DescontosInssDecimoTerceiro: data.DescontosInssDecimoTerceiro,
    DescontosInssRescisao: data.DescontosInssRescisao,
    DescontosIrrf: data.DescontosIrrf,
    DescontosIrrfFerias: data.DescontosIrrfFerias,
    DescontosIrrfDecimoTerceiro: data.DescontosIrrfDecimoTerceiro,
    DescontosIrrfRescisao: data.DescontosIrrfRescisao,
    DescontosAuxilios: data.DescontosAuxilios,
    DescontosDsr: data.DescontosDsr,
    DescontosAntecipacaoFolha: data.DescontosAntecipacaoFolha,
    DescontosPagamentoIndevido: data.DescontosPagamentoIndevido,
    DescontosEstorno: data.DescontosEstorno,
    DescontosFaltas: data.DescontosFaltas,
    DescontosNaoDedutiveis: data.DescontosNaoDedutiveis,
    DescontosPlanoSaude: data.DescontosPlanoSaude,
    DescontosValeTransporteIndividualizado:
      data.DescontosValeTransporteIndividualizado,
    DescontosArredondamentoSaldoDesconto:
      data.DescontosArredondamentoSaldoDesconto,
    DescontosMultaRescisaoAntecipado: data.DescontosMultaRescisaoAntecipado,
    DescontosAvisoPrevio: data.DescontosAvisoPrevio,
    DescontosPrimeiraParcelaDecimoTerceiro:
      data.DescontosPrimeiraParcelaDecimoTerceiro,
    DescontosAdiantamentoDecimoTerceiro:
      data.DescontosAdiantamentoDecimoTerceiro,
    DecimoTerceiroOutrosDescontos: data.DecimoTerceiroOutrosDescontos,
    DescontosArredondamento: data.DescontosArredondamento,
    DescontosEmprestimosConsignados: data.DescontosEmprestimosConsignados,
    DescontosMultaRescisoria: data.DescontosMultaRescisoria,
    DescontosContribuicaoSindicalMensal:
      data.DescontosContribuicaoSindicalMensal,
    DescontosContribuicaoSindicalAnual: data.DescontosContribuicaoSindicalAnual,
    DescontosAdiantamentoSalario: data.DescontosAdiantamentoSalario,
    DescontosConvenios: data.DescontosConvenios,
    DescontosSeguroVida: data.DescontosSeguroVida,
    DescontosOutros: data.DescontosOutros,
    PensaoAlimenticia: data.PensaoAlimenticia,
    BasePisSemFolha: data.BasePisSemFolha,
    BasePisDecimoTerceiroSemFolha: data.BasePisDecimoTerceiroSemFolha,
    BasePisFeriasSemFolha: data.BasePisFeriasSemFolha,
    BasePisRescisaoSemFolha: data.BasePisRescisaoSemFolha,
    BaseFgts: data.BaseFgts,
    BaseFgtsDecimoTerceiro: data.BaseFgtsDecimoTerceiro,
    BaseFgtsFerias: data.BaseFgtsFerias,
    BaseFgtsRescisao: data.BaseFgtsRescisao,
    BaseFgtsDemitidos: data.BaseFgtsDemitidos,
    BaseFgtsDecimoTerceiroDemitidos: data.BaseFgtsDecimoTerceiroDemitidos,
    BaseIrrf: data.BaseIrrf,
    BaseIrrfDecimoTerceiro: data.BaseIrrfDecimoTerceiro,
    BaseIrrfFerias: data.BaseIrrfFerias,
    BaseIrrfRescisao: data.BaseIrrfRescisao,
    BaseIrrfPlrAnual: data.BaseIrrfPlrAnual,
    BaseInss: data.BaseInss,
    BaseInssDecimoTerceiro: data.BaseInssDecimoTerceiro,
    BaseInssFerias: data.BaseInssFerias,
    BaseInssRescisao: data.BaseInssRescisao,
    InssPatronal: data.InssPatronal,
    InssTerceiros   : data.InssTerceiros,
    RatFap: data.RatFap,
    DeducoesGps: data.DeducoesGps,
    Grrf: data.Grrf,
    EncargosSobreRescisao: data.EncargosSobreRescisao,
    Fgts: data.Fgts,
    FgtsDecimoTerceiro: data.FgtsDecimoTerceiro,
    FgtsFerias: data.FgtsFerias,
    FgtsRescisao: data.FgtsRescisao,
    FgtsRescisaoAntecipada: data.FgtsRescisaoAntecipada,
    PisSemFolha: data.PisSemFolha,
    ValorBrutoRPA: data.ValorBrutoRPA,
    IssRPA: data.IssRPA,
    DescontoInssRPA: data.DescontoInssRPA,
    ValorLiquidoRPA: data.ValorLiquidoRPA,
    InssRPAPatronal: data.InssRPAPatronal,
    IrrfSRPA: data.IrrfSRPA,
    FolhaPagamentoUnidade: (data.FolhaPagamentoUnidade ?? []).map(
      (unit: any) => ({
        Id: unit.Id,
        UnidadeId: unit.UnidadeId,
        LinhaServicoId: unit.LinhaServicoId,
        AreaAtuacaoId: unit.AreaAtuacaoId,
        CargaHorariaSemanalId: unit.CargaHorariaSemanalId,
      })
    ),



  };
};
