import { cargaHoraria } from "../data/CargaHoraria";
import { cargos } from "../data/Cargos";
import { funcionarios } from "../data/Funcionarios";
import { prestacao } from "../data/prestacaoData";
import { PayRollDTO } from "../entities/payRoll";

const limpacpf = (cpf: string):string => {
  if(!cpf) return ""
  return cpf.replace(/\D/g, "").padStart(11, "0");
}

export const mapperPayRoll = (data: any): PayRollDTO => {
  console.log("Nascimento:", data.dataNascimento)
  return {
    // id: data.Id,
    ParceriaId: 43,//data.ParceriaId,
    PrestacaoContaId: prestacao.find(p => p.mes === Number(data.mes))?.id || 0,
    FuncionarioId: funcionarios.find(f=>f.CPF === limpacpf(data.cpf))?.Id || 0,//ajustar data.FuncionarioId
    Nome: data.nome,
    CPF: data.cpf,
    DataNascimento: new Date(data.dataNascimento),
    CargoId: cargos.find(c=>c.CBO === data.categoriaProfissionalCBO)?.Id || 0,
    TipoColaborador: Number((data.tipoColaboradorId || "0").replace(",", ".")),
    TipoCoordenadoria: 1 ,//Number(data.tipoCoordenadoria),
    RegimeContratacao: Number((data.regimeContratacaoId || "0").replace(",", ".")),
    CnsDoProfissional: data.cnsProfissional,
    TipoAtividade: Number((data.tipoAtividadeId || "0").replace(",", ".")),
    TipoFolha: Number((data.tipoFolhaId || "0").replace(",", ".")),
    TipoJornada: Number((data.jornada || "0").replace(",", ".")),
    FuncaoId: Number((data.funcaoId || "0").replace(",", ".")),
    DataAdmissao: new Date(data.dataAdmissao),
    DataDesligamento: data.dataDesligamento ? new Date(data.DataDesligamento) : null,
    NumConselhoClasse: data.nConselhoClasse,
    AutoDeclaracaoRacial: Number((data.autodeclaracaoRacialId || "0").replace(",", ".")),
    NomeSocial: data.nomeSocial,
    AutoDeclaracaoGenero: Number((data.identidadeGenero || "0").replace(",", ".")),
    Especificacao: "",
    SalarioBase: Number((data.salarioBase || "0").replace(",", ".")),
    SalarioBruto: Number((data.salarioBruto || "0").replace(",", ".")),
    SalarioLiquido: Number((data.salarioLiquido || "0").replace(",", ".")),
    Gratificacao: Number((data.gratificacao || "0").replace(",", ".")),
    HorasExtras: Number((data.horasExtras || "0").replace(",", ".")),
    HorasExtrasDsr: Number((data.horaExtraDsr || "0").replace(",", ".")),
    AdicionalNoturno: Number((data.adicionalNoturno || "0").replace(",", ".")),
    AdicionalNoturnoDsr: Number((data.adicionalNoturnoDsr || "0").replace(",", ".")),
    Premio: Number((data.premio || "0").replace(",", ".")),
    AdicionalPericulosidade: Number((data.adicionalPericulosidade || "0").replace(",", ".")),
    AdicionalInsalubridade: Number((data.adicionalInsalubridade || "0").replace(",", ".")),
    DiferencaSalarial: Number((data.diferencaSalarial || "0").replace(",", ".")),
    SalarioFamilia: Number((data.salarioFamilia || "0").replace(",", ".")),
    SalarioMaternidade: Number((data.salarioMaternidade || "0").replace(",", ".")),
    RestituicaoInss: Number((data.restituicaoInss || "0").replace(",", ".")),
    RestituicaoIrrf: Number((data.restituicaoIrrf || "0").replace(",", ".")),
    AdiantamentoSalario: Number((data.adiantamentoSalario || "0").replace(",", ".")),
    Devolucao: Number((data.devolucao || "0").replace(",", ".")),
    Arredondamento: 0,
    AtestadoAteQuinzeDias: 0,
    OutrosProventos: Number((data.outrosProventos || "0").replace(",", ".")),
    Ferias: Number((data.ferias || "0").replace(",", ".")),
    FeriaAbono: Number((data.feriasAbono || "0").replace(",", ".")),
    FeriasProximoMes: Number((data.feriasProximoMes || "0").replace(",", ".")),
    AbonoPecuniario: Number((data.abonoPecuniario || "0").replace(",", ".")),
    DecimoTerceiroPrimeiraParcela: Number((data.decimoTerceiroPrimeiraParcela || "0").replace(",", ".")),
    DecimoTerceiroSegundaParcela: Number((data.decimoTerceiroSegundaParcela || "0").replace(",", ".")),
    SaldoSalarioRescisao: Number((data.saldoSalarioRescisao || "0").replace(",", ".")),
    FeriasProporcionaisRescisao: Number((data.feriasProporcionaisRescisao || "0").replace(",", ".")),
    FeriasProporcionaisRescisaoUmTercoAdicional: Number((data.feriasProporcionaisRescisaoUmTercoAdicional || "0").replace(",", ".")),
    DecimoTerceiroProporcionalRescisao: Number((data.decimoTerceiroProporcionalRescisao || "0").replace(",", ".")),
    DecimoTerceiroIndenizado: Number((data.decimoTerceiroIndenizado || "0").replace(",", ".")),
    MultaRescisao: Number((data.multaRescisao || "0").replace(",", ".")),
    OutrasVerbasRescisorias: Number((data.outrasVerbasRescisorias || "0").replace(",", ".")),
    ValorBrutoRescisao: Number((data.valorBrutoRescisao || "0").replace(",", ".")),
    ValorLiquidoRescisaoAPagar: Number((data.valorLiquidoRescisaoAPagar || "0").replace(",", ".")),
    PlantaoMensal: Number((data.plantaoMensal || "0").replace(",", ".")),
    ValeTransporte: Number((data.valeTransporte || 0 || "0").replace(",", ".")),
    ValeAlimentacao: Number((data.valeAlimentacao || "0").replace(",", ".")),
    ValeRefeicao: Number((data.valeRefeicao || 0 || "0").replace(",", ".")),
    CestaBasica: Number((data.cestaBasica || "0").replace(",", ".")),
    AuxilioCreche: Number((data.auxilioCreche || "0").replace(",", ".")),
    Auxilios: 0,
    OutrosBeneficios: Number((data.outrosBeneficios || "0").replace(",", ".")),
    DescontosInss: Number((data.inss || "0").replace(",", ".")),
    DescontosInssFerias: Number((data.inssFerias || "0").replace(",", ".")),
    DescontosInssDecimoTerceiro: Number((data.inssDecimoTerceiro || "0").replace(",", ".")),
    DescontosInssRescisao: Number((data.inssRescisao || "0").replace(",", ".")),
    DescontosIrrf: Number((data.irrf || "0").replace(",", ".") || "0"),
    DescontosIrrfFerias: Number((data.irrfFerias || "0").replace(",", ".")),
    DescontosIrrfDecimoTerceiro: Number((data.irrfDecimoTerceiro || "0").replace(",", ".")),
    DescontosIrrfRescisao: Number((data.irrfRescisao || "0").replace(",", ".")),
    DescontosAuxilios: Number((data.descontoAuxilios || "0").replace(",", ".")),
    DescontosDsr: Number((data.descontoDsr || "0").replace(",", ".")),
    DescontosAntecipacaoFolha: Number((data.antecipacaoFolha || "0").replace(",", ".")),
    DescontosPagamentoIndevido: Number((data.descontoPagtoIndevido || "0").replace(",", ".")),
    DescontosEstorno: Number((data.estornos || "0").replace(",", ".")),
    DescontosFaltas: Number((data.faltas || "0").replace(",", ".")),
    DescontosNaoDedutiveis: Number((data.descontosNaoDedutiveis || "0").replace(",", ".")),
    DescontosPlanoSaude: Number((data.planoSaude || "0").replace(",", ".")),
    DescontosValeTransporteIndividualizado: Number((data.valeTransporteIndividualizado || "0").replace(",", ".")),
    DescontosArredondamentoSaldoDesconto: Number((data.descontoArredondamento || "0").replace(",", ".")),
    DescontosMultaRescisaoAntecipado: Number((data.descontoMultaRescisaoAntecipada || "0").replace(",", ".")),
    DescontosAvisoPrevio: Number((data.descontoAvisoPrevio || "0").replace(",", ".")),
    DescontosPrimeiraParcelaDecimoTerceiro: Number((data.descontoPrimeiraParcelaDecimoTerceiro || "0").replace(",", ".")),
    DescontosAdiantamentoDecimoTerceiro: Number((data.descontoAdiantamentoDecimoTerceiro || "0").replace(",", ".")),
    DecimoTerceiroOutrosDescontos: Number((data.decimoTerceiroOutrosDescontos || "0").replace(",", ".")),
    DescontosArredondamento: Number((data.descontoArredondamento || "0").replace(",", ".")),
    DescontosEmprestimosConsignados: Number((data.emprestimosConsignados || "0").replace(",", ".")),
    DescontosMultaRescisoria: Number((data.multaRescisoria || "0").replace(",", ".")),
    DescontosContribuicaoSindicalMensal: Number((data.contribuicaoSindicalMensal || "0").replace(",", ".")),
    DescontosContribuicaoSindicalAnual: Number((data.contribuicaoSindicalAnual || "0").replace(",", ".")),
    DescontosAdiantamentoSalario: Number((data.descontoAdiantamentoSalario || "0").replace(",", ".")),
    DescontosConvenios: Number((data.descontoConvenios || "0").replace(",", ".")),
    DescontosSeguroVida: Number((data.descontoSeguroVida || "0").replace(",", ".")),
    DescontosOutros: Number((data.outrosDescontos || "0").replace(",", ".")),
    PensaoAlimenticia: Number((data.pensaoAlimenticia || "0").replace(",", ".")),
    BasePisSemFolha: Number((data.basePisSemFolha || "0").replace(",", ".")),
    BasePisDecimoTerceiroSemFolha: Number((data.basePisDecimoTerceiroSemFolha || "0").replace(",", ".")),
    BasePisFeriasSemFolha: Number((data.basePisFeriasSemFolha || "0").replace(",", ".")),
    BasePisRescisaoSemFolha: Number((data.basePisRescisaoSemFolha || "0").replace(",", ".")),
    BaseFgts: Number((data.baseFgts || "0").replace(",", ".")),
    BaseFgtsDecimoTerceiro: Number((data.baseFgtsDecimoTerceiro || "0").replace(",", ".")),
    BaseFgtsFerias: Number((data.baseFgtsFerias || "0").replace(",", ".")),
    BaseFgtsRescisao: Number((data.baseFgtsRescisao || "0").replace(",", ".")),
    BaseFgtsDemitidos: Number((data.baseFgtsDemitidos || "0").replace(",", ".")),
    BaseFgtsDecimoTerceiroDemitidos: Number((data.baseFgtsDecimoTerceiroDemitidos || "0").replace(",", ".")),
    BaseIrrf: Number((data.baseIrrf || "0").replace(",", ".")),
    BaseIrrfDecimoTerceiro: Number((data.baseIrrfDecimoTerceiro || "0").replace(",", ".")),
    BaseIrrfFerias: Number((data.baseIrrfFerias || "0").replace(",", ".")),
    BaseIrrfRescisao: Number((data.baseIrrfRescisao || "0").replace(",", ".")),
    BaseIrrfPlrAnual: Number((data.baseIrrfPlrAnual || "0").replace(",", ".")),
    BaseInss: Number((data.baseInss || "0").replace(",", ".")),
    BaseInssDecimoTerceiro: Number((data.baseInssDecimoTerceiro || "0").replace(",", ".")),
    BaseInssFerias: Number((data.baseInssFerias || "0").replace(",", ".")),
    BaseInssRescisao: Number((data.baseInssRescisao || "0").replace(",", ".")),
    InssPatronal: Number((data.inssPatronal || "0").replace(",", ".")),
    InssTerceiros: Number((data.inssTerceiros || "0").replace(",", ".")),
    RatFap: Number((data.ratFap || "0").replace(",", ".")),
    DeducoesGps: Number((data.deducoesGps || "0").replace(",", ".")),
    Grrf: Number((data.grrf || "0").replace(",", ".")),
    EncargosSobreRescisao: Number((data.encargosSobreRescisao || "0").replace(",", ".")),
    Fgts: Number((data.fgts || "0").replace(",", ".")),
    FgtsDecimoTerceiro: Number((data.fgtsDecimoTerceiro || "0").replace(",", ".")),
    FgtsFerias: Number((data.fgtsFerias || "0").replace(",", ".")),
    FgtsRescisao: Number((data.fgtsRescisao || "0").replace(",", ".")), 
    FgtsRescisaoAntecipada:  0,
    PisSemFolha: Number((data.pisSemFolha || "0").replace(",", ".")),
    ValorBrutoRPA: Number((data.valorBrutoRpa || "0").replace(",", ".")),
    IssRPA: Number((data.issSemRpa || "0").replace(",", ".")),
    DescontoInssRPA: Number((data.inssRetidoSemRpa || "0").replace(",", ".")),
    ValorLiquidoRPA: Number((data.valorLiquidoRpa || "0").replace(",", ".")),
    InssRPAPatronal: Number((data.inssPatronal || "0").replace(",", ".")),
    IrrfSRPA: Number((data.irrfSemRpa || "0").replace(",", ".")),
    FolhaPagamentoUnidade: [
      {
        // Id:""),
        UnidadeId: 1,
        LinhaServicoId: 43,
        AreaAtuacaoId: Number((data.areaAtuacaoId || "0").replace(",", ".")),
        CargaHorariaSemanalId: cargaHoraria.find(c=>c.Horas === Number(data.cargaHoraria))?.Id || 0,
      }
    ] 
    
  };
};
