import { cargaHoraria } from "../data/CargaHoraria";
import { cargos } from "../data/Cargos";
import { funcionarios } from "../data/Funcionarios";
import { prestacao } from "../data/prestacaoData";
import { PayRollDTO } from "../entities/payRoll";

const limpacpf = (cpf: string):string => {
  if(!cpf) return ""
  return cpf.replace(/\D/g, "").padStart(11, "0");
}

export const mapperPayRoll = (data: any): PayRollDTO => {
  return {
    // id: data.Id,
    ParceriaId: 43,//data.ParceriaId,
    PrestacaoContaId: prestacao.find(p => p.mes === Number(data.mes))?.id || 0,
    FuncionarioId: funcionarios.find(f=>f.CPF === limpacpf(data.cpf))?.Id || 0,//ajustar data.FuncionarioId
    Nome: data.nome,
    CPF: data.cpf,
    DataNascimento: new Date(data.dataNascimento),
    CargoId: cargos.find(c=>c.CBO === data.categoriaProfissionalCBO)?.Id || 0,
    TipoColaborador: Number(data.tipoColaboradorId),
    TipoCoordenadoria: Number(data.tipoCoordenadoria),
    RegimeContratacao: Number(data.regimeContratacaoId),
    CnsDoProfissional: data.cnsProfissional,
    TipoAtividade: Number(data.tipoAtividadeId),
    TipoFolha: Number(data.tipoFolhaId),
    TipoJornada: Number(data.jornada),
    FuncaoId: Number(data.funcaoId),
    DataAdmissao: new Date(data.dataAdmissao),
    DataDesligamento: data.dataDesligamento ? new Date(data.DataDesligamento) : null,
    NumConselhoClasse: data.nConselhoClasse,
    AutoDeclaracaoRacial: Number(data.autodeclaracaoRacialId),
    NomeSocial: data.nomeSocial,
    AutoDeclaracaoGenero: Number(data.identidadeGenero),
    Especificacao: "",
    SalarioBase: Number(data.salarioBase),
    SalarioBruto: Number(data.salarioBruto),
    SalarioLiquido: Number(data.salarioLiquido),
    Gratificacao: Number(data.gratificacao),
    HorasExtras: Number(data.horasExtras),
    HorasExtrasDsr: Number(data.horaExtraDsr),
    AdicionalNoturno: Number(data.adicionalNoturno),
    AdicionalNoturnoDsr: Number(data.adicionalNoturnoDsr),
    Premio: Number(data.premio),
    AdicionalPericulosidade: Number(data.adicionalPericulosidade),
    AdicionalInsalubridade: Number(data.adicionalInsalubridade),
    DiferencaSalarial: Number(data.diferencaSalarial),
    SalarioFamilia: Number(data.salarioFamilia),
    SalarioMaternidade: Number(data.salarioMaternidade),
    RestituicaoInss: Number(data.restituicaoInss),
    RestituicaoIrrf: Number(data.restituicaoIrrf),
    AdiantamentoSalario: Number(data.adiantamentoSalario),
    Devolucao: Number(data.devolucao),
    Arredondamento: 0,
    AtestadoAteQuinzeDias: 0,
    OutrosProventos: Number(data.outrosProventos),
    Ferias: Number(data.ferias),
    FeriaAbono: Number(data.feriasAbono),
    FeriasProximoMes: Number(data.feriasProximoMes),
    AbonoPecuniario: Number(data.abonoPecuniario),
    DecimoTerceiroPrimeiraParcela: Number(data.decimoTerceiroPrimeiraParcela),
    DecimoTerceiroSegundaParcela: Number(data.decimoTerceiroSegundaParcela),
    SaldoSalarioRescisao: Number(data.saldoSalarioRescisao),
    FeriasProporcionaisRescisao: Number(data.feriasProporcionaisRescisao),
    FeriasProporcionaisRescisaoUmTercoAdicional: Number(data.feriasProporcionaisRescisaoUmTercoAdicional),
    DecimoTerceiroProporcionalRescisao: Number(data.decimoTerceiroProporcionalRescisao),
    DecimoTerceiroIndenizado: Number(data.decimoTerceiroIndenizado),
    MultaRescisao: Number(data.multaRescisao),
    OutrasVerbasRescisorias: Number(data.outrasVerbasRescisorias),
    ValorBrutoRescisao: Number(data.valorBrutoRescisao),
    ValorLiquidoRescisaoAPagar: Number(data.valorLiquidoRescisaoAPagar),
    PlantaoMensal: Number(data.plantaoMensal),
    ValeTransporte: Number(data.valeTransporte || 0),
    ValeAlimentacao: Number(data.valeAlimentacao),
    ValeRefeicao: Number(data.valeRefeicao || 0),
    CestaBasica: Number(data.cestaBasica),
    AuxilioCreche: Number(data.auxilioCreche),
    Auxilios: 0,
    OutrosBeneficios: Number(data.outrosBeneficios),
    DescontosInss: Number(data.inss),
    DescontosInssFerias: Number(data.inssFerias),
    DescontosInssDecimoTerceiro: Number(data.inssDecimoTerceiro),
    DescontosInssRescisao: Number(data.inssRescisao),
    DescontosIrrf: Number(data.irrf),
    DescontosIrrfFerias: Number(data.irrfFerias),
    DescontosIrrfDecimoTerceiro: Number(data.irrfDecimoTerceiro),
    DescontosIrrfRescisao: Number(data.irrfRescisao),
    DescontosAuxilios: Number(data.descontoAuxilios),
    DescontosDsr: Number(data.descontoDsr),
    DescontosAntecipacaoFolha: Number(data.antecipacaoFolha),
    DescontosPagamentoIndevido: Number(data.descontoPagtoIndevido),
    DescontosEstorno: Number(data.estornos),
    DescontosFaltas: Number(data.faltas),
    DescontosNaoDedutiveis: Number(data.descontosNaoDedutiveis),
    DescontosPlanoSaude: Number(data.planoSaude),
    DescontosValeTransporteIndividualizado: Number(data.valeTransporteIndividualizado),
    DescontosArredondamentoSaldoDesconto: Number(data.descontoArredondamento),
    DescontosMultaRescisaoAntecipado: Number(data.descontoMultaRescisaoAntecipada),
    DescontosAvisoPrevio: Number(data.descontoAvisoPrevio),
    DescontosPrimeiraParcelaDecimoTerceiro: Number(data.descontoPrimeiraParcelaDecimoTerceiro),
    DescontosAdiantamentoDecimoTerceiro: Number(data.descontoAdiantamentoDecimoTerceiro),
    DecimoTerceiroOutrosDescontos: Number(data.decimoTerceiroOutrosDescontos),
    DescontosArredondamento: Number(data.descontoArredondamento),
    DescontosEmprestimosConsignados: Number(data.emprestimosConsignados),
    DescontosMultaRescisoria: Number(data.multaRescisoria),
    DescontosContribuicaoSindicalMensal: Number(data.contribuicaoSindicalMensal),
    DescontosContribuicaoSindicalAnual: Number(data.contribuicaoSindicalAnual),
    DescontosAdiantamentoSalario: Number(data.descontoAdiantamentoSalario),
    DescontosConvenios: Number(data.descontoConvenios),
    DescontosSeguroVida: Number(data.descontoSeguroVida),
    DescontosOutros: Number(data.outrosDescontos),
    PensaoAlimenticia: Number(data.pensaoAlimenticia),
    BasePisSemFolha: Number(data.basePisSemFolha),
    BasePisDecimoTerceiroSemFolha: Number(data.basePisDecimoTerceiroSemFolha),
    BasePisFeriasSemFolha: Number(data.basePisFeriasSemFolha),
    BasePisRescisaoSemFolha: Number(data.basePisRescisaoSemFolha),
    BaseFgts: Number(data.baseFgts),
    BaseFgtsDecimoTerceiro: Number(data.baseFgtsDecimoTerceiro),
    BaseFgtsFerias: Number(data.baseFgtsFerias),
    BaseFgtsRescisao: Number(data.baseFgtsRescisao),
    BaseFgtsDemitidos: Number(data.baseFgtsDemitidos),
    BaseFgtsDecimoTerceiroDemitidos: Number(data.baseFgtsDecimoTerceiroDemitidos),
    BaseIrrf: Number(data.baseIrrf),
    BaseIrrfDecimoTerceiro: Number(data.baseIrrfDecimoTerceiro),
    BaseIrrfFerias: Number(data.baseIrrfFerias),
    BaseIrrfRescisao: Number(data.baseIrrfRescisao),
    BaseIrrfPlrAnual: Number(data.baseIrrfPlrAnual),
    BaseInss: Number(data.baseInss),
    BaseInssDecimoTerceiro: Number(data.baseInssDecimoTerceiro),
    BaseInssFerias: Number(data.baseInssFerias),
    BaseInssRescisao: Number(data.baseInssRescisao),
    InssPatronal: Number(data.inssPatronal),
    InssTerceiros: Number(data.inssTerceiros),
    RatFap: Number(data.ratFap),
    DeducoesGps: Number(data.deducoesGps),
    Grrf: Number(data.grrf),
    EncargosSobreRescisao: Number(data.encargosSobreRescisao),
    Fgts: Number(data.fgts),
    FgtsDecimoTerceiro: Number(data.fgtsDecimoTerceiro),
    FgtsFerias: Number(data.fgtsFerias),
    FgtsRescisao: Number(data.fgtsRescisao), 
    FgtsRescisaoAntecipada: 0,
    PisSemFolha: Number(data.pisSemFolha),
    ValorBrutoRPA: Number(data.valorBrutoRpa),
    IssRPA: Number(data.issSemRpa),
    DescontoInssRPA: Number(data.inssRetidoSemRpa),
    ValorLiquidoRPA: Number(data.valorLiquidoRpa),
    InssRPAPatronal: Number(data.inssPatronal),
    IrrfSRPA: Number(data.irrfSemRpa),
    FolhaPagamentoUnidade: [
      {
        // Id:""),
        UnidadeId: 1,
        LinhaServicoId: 43,
        AreaAtuacaoId: Number(data.areaAtuacaoId),
        CargaHorariaSemanalId: cargaHoraria.find(c=>c.Horas === Number(data.cargaHoraria))?.Id || 0,
      }
    ] 
    
  };
};
